### ISSUE TITLE
Missing https://github.com/cedx/enum.php

### ISSUE THREAD

**Issue by bilogic** [cedx/enum.js#6]
Hi,

I need this library because of this https://github.com/sitelease/sugar-cube-client, but it is no longer available. Can share a copy of it? Thank you!

**Comment by cedx** [comment]
I've removed a long time ago this library from GitHub and Packagist: nearly nobody was using it (including me!).
If you upgrade to the latest version of https://github.com/sitelease/sugar-cube-client, everything should be OK as its author has replaced my library by a better one.
See: https://github.com/sitelease/sugar-cube-client/commit/5deac6cf558c021d17b84c38083853c7b0ed7669
